version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - DB_PORT:5432